package model;
// Generated Oct 25, 2018 10:38:53 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DonnerId generated by hbm2java
 */
@Embeddable
public class DonnerId implements java.io.Serializable {

	private int idStagiaire;
	private int idProposition;

	public DonnerId() {
	}

	public DonnerId(int idStagiaire, int idProposition) {
		this.idStagiaire = idStagiaire;
		this.idProposition = idProposition;
	}

	@Column(name = "idStagiaire", nullable = false)
	public int getIdStagiaire() {
		return this.idStagiaire;
	}

	public void setIdStagiaire(int idStagiaire) {
		this.idStagiaire = idStagiaire;
	}

	@Column(name = "idProposition", nullable = false)
	public int getIdProposition() {
		return this.idProposition;
	}

	public void setIdProposition(int idProposition) {
		this.idProposition = idProposition;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DonnerId))
			return false;
		DonnerId castOther = (DonnerId) other;

		return (this.getIdStagiaire() == castOther.getIdStagiaire())
				&& (this.getIdProposition() == castOther.getIdProposition());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdStagiaire();
		result = 37 * result + this.getIdProposition();
		return result;
	}

}
