package model;
// Generated Oct 25, 2018 10:38:53 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Formateur generated by hbm2java
 */
@Entity
@Table(name = "formateur", catalog = "QUIZ2")
public class Formateur implements java.io.Serializable {

	private Integer idFormateur;
	private String nomFormateur;
	private String prenomFormateur;
	private String mailFormateur;
	private String mdpFormateur;
	private Set<Quiz> quizs = new HashSet<Quiz>(0);
	
	public Formateur() {
	}

	public Formateur(int idFormateur) {
		this.idFormateur = idFormateur;
	}

	public Formateur(String nomFormateur, String prenomFormateur, String mailFormateur, String mdpFormateur) {
		this.nomFormateur = nomFormateur;
		this.prenomFormateur = prenomFormateur;
		this.mailFormateur = mailFormateur;
		this.mdpFormateur = mdpFormateur;
	}

	public Formateur(String nomFormateur, String prenomFormateur, String mailFormateur, String mdpFormateur,
			Set<Quiz> quizs) {
		this.nomFormateur = nomFormateur;
		this.prenomFormateur = prenomFormateur;
		this.mailFormateur = mailFormateur;
		this.mdpFormateur = mdpFormateur;
		this.quizs = quizs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idFormateur", unique = true, nullable = false)
	public Integer getIdFormateur() {
		return this.idFormateur;
	}

	public void setIdFormateur(Integer idFormateur) {
		this.idFormateur = idFormateur;
	}

	@Column(name = "nomFormateur", nullable = false, length = 32)
	public String getNomFormateur() {
		return this.nomFormateur;
	}

	public void setNomFormateur(String nomFormateur) {
		this.nomFormateur = nomFormateur;
	}

	@Column(name = "prenomFormateur", nullable = false, length = 32)
	public String getPrenomFormateur() {
		return this.prenomFormateur;
	}

	public void setPrenomFormateur(String prenomFormateur) {
		this.prenomFormateur = prenomFormateur;
	}

	@Column(name = "mailFormateur", nullable = false, length = 32)
	public String getMailFormateur() {
		return this.mailFormateur;
	}

	public void setMailFormateur(String mailFormateur) {
		this.mailFormateur = mailFormateur;
	}

	@Column(name = "mdpFormateur", nullable = false, length = 128)
	public String getMdpFormateur() {
		return this.mdpFormateur;
	}

	public void setMdpFormateur(String mdpFormateur) {
		this.mdpFormateur = mdpFormateur;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formateur")
	public Set<Quiz> getQuizs() {
		return this.quizs;
	}

	public void setQuizs(Set<Quiz> quizs) {
		this.quizs = quizs;
	}

}
