package model;
// Generated Oct 25, 2018 10:38:53 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "module", catalog = "QUIZ2")
public class Module implements java.io.Serializable {

	private Integer idModule;
	private Theme theme;
	private String nomModule;
	private Set<Quiz> quizs = new HashSet<Quiz>(0);

	public Module() {
	}

	public Module(Theme theme, String nomModule) {
		this.theme = theme;
		this.nomModule = nomModule;
	}

	public Module(Theme theme, String nomModule, Set<Quiz> quizs) {
		this.theme = theme;
		this.nomModule = nomModule;
		this.quizs = quizs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idModule", unique = true, nullable = false)
	public Integer getIdModule() {
		return this.idModule;
	}

	public void setIdModule(Integer idModule) {
		this.idModule = idModule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTheme", nullable = false)
	public Theme getTheme() {
		return this.theme;
	}

	public void setTheme(Theme theme) {
		this.theme = theme;
	}

	@Column(name = "nomModule", nullable = false, length = 64)
	public String getNomModule() {
		return this.nomModule;
	}

	public void setNomModule(String nomModule) {
		this.nomModule = nomModule;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<Quiz> getQuizs() {
		return this.quizs;
	}

	public void setQuizs(Set<Quiz> quizs) {
		this.quizs = quizs;
	}

}
