package model;
// Generated Oct 25, 2018 10:38:53 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PasserId generated by hbm2java
 */
@Embeddable
public class PasserId implements java.io.Serializable {

	private int idStagiaire;
	private int idTest;

	public PasserId() {
	}

	public PasserId(int idStagiaire, int idTest) {
		this.idStagiaire = idStagiaire;
		this.idTest = idTest;
	}

	@Column(name = "idStagiaire", unique = true, nullable = false)
	public int getIdStagiaire() {
		return this.idStagiaire;
	}

	public void setIdStagiaire(int idStagiaire) {
		this.idStagiaire = idStagiaire;
	}

	@Column(name = "idTest", nullable = false)
	public int getIdTest() {
		return this.idTest;
	}

	public void setIdTest(int idTest) {
		this.idTest = idTest;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PasserId))
			return false;
		PasserId castOther = (PasserId) other;

		return (this.getIdStagiaire() == castOther.getIdStagiaire()) && (this.getIdTest() == castOther.getIdTest());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdStagiaire();
		result = 37 * result + this.getIdTest();
		return result;
	}

}
