package model;
// Generated Oct 25, 2018 10:38:53 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Passer generated by hbm2java
 */
@Entity
@Table(name = "passer", catalog = "QUIZ2", uniqueConstraints = @UniqueConstraint(columnNames = "idStagiaire"))
public class Passer implements java.io.Serializable {

	private PasserId id;
	private Quiz quiz;
	private Stagiaire stagiaire;
	private int note;

	public Passer() {
	}

	public Passer(PasserId id, Quiz quiz, Stagiaire stagiaire, int note) {
		this.id = id;
		this.quiz = quiz;
		this.stagiaire = stagiaire;
		this.note = note;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idStagiaire", column = @Column(name = "idStagiaire", unique = true, nullable = false)),
			@AttributeOverride(name = "idTest", column = @Column(name = "idTest", nullable = false)) })
	public PasserId getId() {
		return this.id;
	}

	public void setId(PasserId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTest", nullable = false, insertable = false, updatable = false)
	public Quiz getQuiz() {
		return this.quiz;
	}

	public void setQuiz(Quiz quiz) {
		this.quiz = quiz;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idStagiaire", unique = true, nullable = false, insertable = false, updatable = false)
	public Stagiaire getStagiaire() {
		return this.stagiaire;
	}

	public void setStagiaire(Stagiaire stagiaire) {
		this.stagiaire = stagiaire;
	}

	@Column(name = "note", nullable = false)
	public int getNote() {
		return this.note;
	}

	public void setNote(int note) {
		this.note = note;
	}

}
