package model;
// Generated Oct 25, 2018 10:38:53 AM by Hibernate Tools 5.1.10.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "QUIZ2")
public class Question implements java.io.Serializable {

	private Integer idQuestion;
	private Quiz quiz;
	private String intituleQuestion;
	private int secondesPourRepondre;
	private List<Proposition> propositions = new ArrayList<Proposition>(0);

	public Question() {
	}

	public Question(Quiz quiz, String intituleQuestion, int secondesPourRepondre) {
		this.quiz = quiz;
		this.intituleQuestion = intituleQuestion;
		this.secondesPourRepondre = secondesPourRepondre;
	}

	public Question(Quiz quiz, String intituleQuestion, int secondesPourRepondre, List<Proposition> propositions) {
		this.quiz = quiz;
		this.intituleQuestion = intituleQuestion;
		this.secondesPourRepondre = secondesPourRepondre;
		this.propositions = propositions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idQuestion", unique = true, nullable = false)
	public Integer getIdQuestion() {
		return this.idQuestion;
	}

	public void setIdQuestion(Integer idQuestion) {
		this.idQuestion = idQuestion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTest", nullable = false)
	public Quiz getQuiz() {
		return this.quiz;
	}

	public void setQuiz(Quiz quiz) {
		this.quiz = quiz;
	}

	@Column(name = "intituleQuestion", nullable = false, length = 65535)
	public String getIntituleQuestion() {
		return this.intituleQuestion;
	}

	public void setIntituleQuestion(String intituleQuestion) {
		this.intituleQuestion = intituleQuestion;
	}

	@Column(name = "secondesPourRepondre", nullable = false)
	public int getSecondesPourRepondre() {
		return this.secondesPourRepondre;
	}

	public void setSecondesPourRepondre(int secondesPourRepondre) {
		this.secondesPourRepondre = secondesPourRepondre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public List<Proposition> getPropositions() {
		return this.propositions;
	}

	public void setPropositions(List<Proposition> propositions) {
		this.propositions = propositions;
	}

}
