package model;
// Generated Oct 25, 2018 10:38:53 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Theme generated by hbm2java
 */
@Entity
@Table(name = "theme", catalog = "QUIZ2")
public class Theme implements java.io.Serializable {

	private Integer idTheme;
	private String nomTheme;
	private Set<Module> modules = new HashSet<Module>(0);

	public Theme() {
	}

	public Theme(String nomTheme) {
		this.nomTheme = nomTheme;
	}

	public Theme(String nomTheme, Set<Module> modules) {
		this.nomTheme = nomTheme;
		this.modules = modules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTheme", unique = true, nullable = false)
	public Integer getIdTheme() {
		return this.idTheme;
	}

	public void setIdTheme(Integer idTheme) {
		this.idTheme = idTheme;
	}

	@Column(name = "nomTheme", nullable = false, length = 64)
	public String getNomTheme() {
		return this.nomTheme;
	}

	public void setNomTheme(String nomTheme) {
		this.nomTheme = nomTheme;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "theme")
	public Set<Module> getModules() {
		return this.modules;
	}

	public void setModules(Set<Module> modules) {
		this.modules = modules;
	}

}
